### ISSUE TITLE
empty ouput files

### ISSUE THREAD

**Issue by Toral-Manvar** [TF-Chan-Lab/miRDeep-P2_pipeline#1]
I have output generated from miRDP2-v1.1.4_pipeline.bash script.
Now, when I am trying to run your script "parse_miRDP2_prediction.pl", empty output is generated.
Command which I used is as follows:

`perl ./miRDeep-P2_pipeline-main/script/parse_miRDP2_prediction.pl miRDP2_predictions_list.txt sample1_miRDP2
`

where, miRDP2_predictions_list.txt file contains only single file generated after running miRDP2-v1.1.4_pipeline.bash as follows

> Sample_1_filter_P_prediction

Kindly help.

**Comment by alanlamsiu** [comment]
Hi Toral-Manvar,

Did you see any error message when you run the `parse_miRDP2_prediction.pl` script? If you could also share the output from miRDP2, I would be able to look into it for you.

Xiao

**Comment by Toral-Manvar** [comment]
Hello Alan,

Sorry for late reply. No there was no error message. I can share the output of miRDeep-p2 but for that can you share your email ID please.

**Comment by alanlamsiu** [comment]
Hi Toral-Manvar,

No worry. Please feel free to share with my email address shown below.

xlin@link.cuhk.edu.hk
