### ISSUE TITLE
miRNA from repetitive region

### ISSUE THREAD

**Issue by rbio123** [TF-Chan-Lab/miRDeep-P2_pipeline#2]
Hi,

I predicted novel miRNA from miRDP2 and getting some miRNA with same sequence (one is upper case like ACGT... and another is lower case like acgt...) from different genomic location. Is it OK or it invalid?

Could please assist me?

Thanks

**Comment by alanlamsiu** [comment]
Hi @rbio123,

I just made a modification. Now in the "To collapse unique mature sequences in mature_wo_U.fa" step, it will convert all small letters to capital ones to generate the unique miRNA sequences, meaning that any sequences with the same letters, regardless whether they are in small or capital letters, will be merged to give the unique sequences. You should be able to use the pipeline now with your input file.

Thanks!
