### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by albenstein** [TF-Chan-Lab/miRDeep-P2_pipeline#4]
Dear Sir or Madam,
We're using miRDP2 on our HPC system. We're getting this error below when we run pipeline.bash:
Could you please help on this issue?
`
Use of uninitialized value $id in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/convert_SAM_to_blast.pl line 87.
Use of uninitialized value $id in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/convert_SAM_to_blast.pl line 87.
Use of uninitialized value $id in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1222.
Use of uninitialized value $id in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1223.
Use of uninitialized value $id in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1224.
Use of uninitialized value $id in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1225.
Use of uninitialized value $subject_old in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 688.
Use of uninitialized value $lng in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 694.
Use of uninitialized value $subject_old in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 789.
Use of uninitialized value $subject_old in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 790.
Use of uninitialized value $subject_old in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 791.
Use of uninitialized value $query in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1046.
Use of uninitialized value $query in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1047.
Use of uninitialized value $query in hash element at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1036.
Use of uninitialized value $end in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1090.
Use of uninitialized value $beg in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1090.
Use of uninitialized value in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1094.
Use of uninitialized value $beg in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1094.
Use of uninitialized value $strand in string eq at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1097.
Use of uninitialized value $beg in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
Use of uninitialized value $beg in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
Use of uninitialized value $end in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
Use of uninitialized value $seq in substr at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
Use of uninitialized value $end in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1114.
Use of uninitialized value $beg in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1114.
Use of uninitialized value in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1118.
Use of uninitialized value $beg in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1118.
Use of uninitialized value $strand in string eq at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1121.
Use of uninitialized value $beg in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1124.
Use of uninitialized value $beg in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1124.
Use of uninitialized value $end in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1124.
Use of uninitialized value $struct in substr at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1124.
Use of uninitialized value $strand in string eq at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 955.
Use of uninitialized value $end in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1090.
Use of uninitialized value $beg in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1090.
Use of uninitialized value in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1094.
Use of uninitialized value $beg in numeric le (<=) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1094.
Use of uninitialized value $strand in string eq at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1097.
Use of uninitialized value $beg in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
Use of uninitialized value $beg in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
Use of uninitialized value $end in subtraction (-) at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
Use of uninitialized value $seq in substr at /cta/capps/mirdeep-p2/1.1.4/scripts/mod-miRDP.pl line 1100.
`

**Comment by albenstein** [comment]
Command is below:
`source miRDP2-v1.1.4_pipeline.bash --bowtie2 -g /cta/users/kkahraman/Fungi_wheat/mirdp2/Data/iwgsc_refseqv2.1_assembly.fa -x /cta/users/kkahraman/Fungi_wheat/mirdp2/Data/Wheat_bowtie_index -f -i /cta/users/kkahraman/Fungi_wheat/mirdp2/Data/HankControl_mirdp2input.fa -o /cta/users/kkahraman/Fungi_wheat/mirdp2/Data/`

Input file:
`>read0_x19440
CATATCGGGTAGGTTGTGGTATTTCATTGC
>read1_x20539
TAATTCATGATCTGGCATGA
>read2_x98
ACAAAAACTATAATAAAGGGGA
>read3_x95783
GGTAGTTCGACCGCGGAAT`

**Comment by albenstein** [comment]
There are ">" characters in each sequence, github is changing them to command.

**Comment by alanlamsiu** [comment]
Got it. After taking a second look at your command, it seems that it is different from what's used in the pipeline in this GitHub page. You should be able to run it if you strictly follow step **1. miRNA prediction using miRDeep-P2**. The command you've used has not been tested in this pipeline.
